
<?php if ($this->getOrders()->getSize() > 0): ?>

    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-rma-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Products') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getOrders() as $order): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $order->getincrement_id() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $order->getCreatedAtFormatted(2) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Products')) ?>" class="col id">
                        <?php foreach($order->getAllItems() as $item): ?>
                            <?php if ($this->canDisplayOrderItem($item)): ?>
                                <?php echo (int)($item->getqty_ordered()); ?>x <?php echo $item->getName(); ?><br>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $order->getStatus() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Select')) ?>" class="col id"><a href="<?php echo $this->getSelectUrl($order); ?>"><?php echo __('Select'); ?></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('No orders available.'); ?></span></div>
<?php endif ?>
