<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}

// $_config = $this->helper('Sm\Destino\Helper\Data');

// $keep_ratio = $_config->getCategoryView('keep_image');
// $image_width = $_config->getCategoryView('image_width');
// $image_height = $_config->getCategoryView('image_height');
// $product_hover = $_config->getCategoryView('hover_image_effect');

// $show_addtocart = $_config->getAdvanced('show_addtocart_button');
// $show_addtocompare = $_config->getAdvanced('show_compare_button');
// $show_addtowishlist = $_config->getAdvanced('show_wishlist_button');

// $show_newlabel = $_config->getAdvanced('show_newlabel');
// $new_label_text = $_config->getAdvanced('new_label_text');

// $show_salelabel = $_config->getAdvanced('show_salelabel');
// $sale_label_text = $_config->getAdvanced('sale_label_text');
// $show_pecent = $_config->getAdvanced('show_salediscount');

?>

<?php if ($exist):?>

	<div class="block-detail">
		<div class="primary-title">
			<h2><?php echo $title; ?></h2>
		</div>
		
		<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">

			<div class="grid products-grid products-<?php echo $type; ?>">
				<div class="grid-product-type products list items product-items related-product-post">

					<?php foreach ($items as $_item): ?>
						<div class="item product product-item">
							<div class="item-inner">
								<div class="product-item-info">
									<div class="product-item-image">
										<a href="<?php echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
											<?php echo $block->getImage($_item, $image)->toHtml(); ?>
										</a>
										
										<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
											<?php if($show_addtowishlist){ ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<a href="#" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
														<span><?php echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>
											
											<?php if($show_addtocompare){ ?>
												<?php if ($block->getAddToCompareUrl()): ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<a href="#" class="action tocompare"
													   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
													   data-role="add-to-links"
													   title="<?php echo __('Add to Compare'); ?>">
														<span><?php echo __('Add to Compare') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>
										</div>
									</div>
									
									
									<div class="product details product-item-details">
										<div class="product name product-item-name">
											<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a>
										</div>

										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
										<?php echo $block->getProductPrice($_item); ?>

										<?php if($show_addtocart){ ?>
											<div class="product-item-inner">
												<div class="product actions product-item-actions">
													<div class="actions-primary">
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
																	<span><?php echo __('Add to Cart') ?></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="action tocart primary"
																		data-post='<?php echo $postData; ?>'
																		type="button" title="<?php echo __('Add to Cart') ?>">
																	<span><?php echo __('Add to Cart') ?></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>	
												</div>
											</div>
										<?php } ?>
									</div>
								</div>	
							</div>
						</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>
	</div>

<script type="text/javascript">
	require([
		'jquery',
		'owlcarousel'
	], function ($) {
		var owl_related_product_post = $(".related-product-post");
		owl_related_product_post.owlCarousel({
			
			responsive:{
				0:{
					items:1
				},
				480:{
					items:2
				},
				768:{
					items:3
				},
				992:{
					items:4
				},
				1200:{
					items:4
				}
			},

			autoplay:false,
			loop:false,
			nav : true, // Show next and prev buttons
			dots: false,
			autoplaySpeed : 500,
			navSpeed : 500,
			dotsSpeed : 500,
			autoplayHoverPause: true,
			margin:20,

		});	  
	});	
</script>
<?php endif;?>