<div class="entry-edit form-inline">
    <div class="fieldset-wrapper customer-information">
        <div class="admin__fieldset-wrapper-title">
            <span class="title"><?php echo __('Personal Information'); ?></span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
                <?php foreach($this->getInformation() as $label => $value): ?>
                    <tr>
                        <th><?php echo $label; ?></th>
                        <td><?php echo $value; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>