<div class="pos_bottom_zone" onclick="objPosCheckout.showShortcutsPopup();">
    Shortcuts
</div>


<div id="shortcuts_popup" class="pos-shortcuts" style="display:none;">
    <?php if ($this->getShortcuts()->getSize() > 0): ?>
        <?php foreach($this->getShortcuts() as $product): ?>
            <div class="pos_product" <?php if ($product->getSellable()): ?>onclick="objPosCheckout.addProduct(<?php echo $product->getId(); ?>, 1); objPosCheckout.closeShortcutPopup();"<?php endif; ?>>
                <img src="<?php echo $product->getImageUrl(); ?>" class="pos_product_image">
                <div class="pos_product_information">
                    <div class="pos_product_name"><?php echo $product->getName(); ?></div>
                    <div class="pos_product_sku"><?php echo $product->getSku(); ?></div>
                    <?php if ($product->getSellable()): ?>
                        <div class="pos_product_stock">Stock: <?php echo $product->getQty(); ?></div>
                    <?php else: ?>
                        <div class="pos_product_oos">This product is out of stock</div>
                    <?php endif; ?>
                    <div class="pos_product_price"><?php echo $this->currencyFormat($product->getPrice()); ?></div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo __('No shortcuts available, to add a product as shortcut, set its POS Shortcut attribute to true and refresh this page'); ?></p>
    <?php endif; ?>
</div>
