<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$nb_column1 = (int)$this->_getConfig('nb_column1', 3);
$_nb_column1 = ($nb_column1 > 0 && $nb_column1 <=6 && $nb_column1 !== 5) ? 12/$nb_column1 : 3;
$nb_column2 = (int)$this->_getConfig('nb_column2', 3);
$_nb_column2 = ($nb_column2 > 0 && $nb_column2 <=6 && $nb_column2 !== 5) ? 12/$nb_column2 : 3;
$nb_column3 = (int)$this->_getConfig('nb_column3', 3);
$_nb_column3 = ($nb_column3 > 0 && $nb_column3 <=6 && $nb_column3 !== 5) ? 12/$nb_column3 : 4;
$nb_column4 = (int)$this->_getConfig('nb_column4', 2);
$_nb_column4 = ($nb_column4 > 0 && $nb_column4 <=6 && $nb_column4 !== 5) ? 12/$nb_column4 : 12;
$check_type = ($this->_getConfig('type_show') == 'slide') ? true : false;

$_cls = (!$check_type) ? 'col-lg-'.$_nb_column1.' col-md-'.$_nb_column2.' col-sm-'.$_nb_column3.' col-xs-'.$_nb_column4.'' : '';

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$showDescription = false;
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$showWishlist = true;
    $showCompare = true;
    $showCart = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$tag_id = "sm_filterproducts_".time().rand()."";
    ?>
	<?php if (!empty($this->_getConfig('title_module'))){?>
	<h2 class="filter-products-title">
		<?php echo $this->_getConfig('title_module') ;?>
	</h2>
	<?php } ?>
    <div id="<?php echo $tag_id; ?>" class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php
		if ($this->_getConfig('product_source') == 'countdown_products') { 
			$dateTo = $this->_getConfig('date_to', '');	
		?>
		<div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>"></div>
		<?php }?>
		
        <?php $iterator = 1; ?>
        <div class="<?php echo $check_type ? ' owl-carousel ' : '';  ?> products list items product-items row filterproducts">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item '.$_cls.'">' : '</div><div class="item product product-item '.$_cls.'">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
					<?php
					if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) { 
						$specialToDate = $_product->getSpecialToDate();
					?>
					<div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>"></div>
					<?php }?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <?php if ($showWishlist || $showCompare || $showCart): ?>
							<div class="product-item-actions">
								<?php if ($showCart): ?>
									<div class="actions-primary">
										<?php if ($_product->isSaleable()): ?>
											<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
												<button class="action tocart primary"
														data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
														type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php
													$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
												?>
												<button class="action tocart primary"
														data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
														type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php endif; ?>
								<?php if ($showWishlist || $showCompare): ?>
									<div class="actions-secondary" data-role="add-to-links">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
											<a href="#"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   class="action towishlist" data-action="add-to-wishlist"
											   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
												<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
										<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
											<a href="#" class="action tocompare"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
											   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
												<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
											</a>
										<?php endif; ?>
									</div>
								<?php endif; ?>
							</div>
						<?php endif; ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
	
	<script type="text/javascript">
        require([
            'jquery'
			<?php if ($check_type) { ?> ,
			'Sm_FilterProducts/js/owl.carousel'
			<?php } ?>
        ], function ($) {
			var $element = $('#<?php echo $tag_id ?>');
			<?php if ($check_type) { ?>
			$('.owl-carousel', $element).owlCarousel({
				loop:true,
				nav:true,
				dots: true,
				autoplay: false,
				autoplayHoverPause: true,
				responsive: {
					0: {
						items:<?php echo $nb_column4;?>
					},
					768: {
						items:<?php echo $nb_column3;?>
					},
					991: {
						items:<?php echo $nb_column2;?>
					},						
					1200: {
						items: <?php echo $nb_column1;?>
					}
				}
			});
			<?php } ?>
			function CountDown(date,id){
				dateNow = new Date();
				amount = date.getTime() - dateNow.getTime();
				delete dateNow;
				if(amount < 0){
					id.html("Now!");
				} else{
					days=0;hours=0;mins=0;secs=0;out="";
					amount = Math.floor(amount/1000);
					days=Math.floor(amount/86400);
					amount=amount%86400;
					hours=Math.floor(amount/3600);
					amount=amount%3600;
					mins=Math.floor(amount/60);
					amount=amount%60;
					secs=Math.floor(amount);
					out += "<div class='deals-time time-day'><div class='num-time'>"+ days +"</div><div class='title-time'>"+((days==1)?"Day":"Days")+"</div></div>";
					out += "<div class='deals-time time-hours'><div class='num-time'>"+ hours +"</div><div class='title-time'>"+((hours==1)?"Hour":"Hours")+"</div></div>";
					out += "<div class='deals-time time-mins'><div class='num-time'>"+ mins +"</div><div class='title-time'>"+((mins==1)?"Min":"Mins")+"</div></div>";
					out += "<div class='deals-time time-secs'><div class='num-time'>"+ secs +"</div><div class='title-time'>"+((secs==1)?"Sec":"Secs")+"</div></div>";
					out = out.substr(0,out.length-2);
					id.html(out);
					setTimeout(function(){CountDown(date,id)}, 1000);
				}
			}
			$( ".deals-countdown",$element).each(function() {
				var timer = $(this).data('timer');
				var data = new Date(timer);
				CountDown(data,$(this));
			});
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
