<?php /** @var $block Oscprofessionals\FranchiseEnquiry\Block\FranchiseEnquiry\Link */ ?>

<div class="franchise-enquiry-button">
    <a href="<?php echo $this->getUrl('franchiseenquiry'); ?>" class="franchise-enquiry-button-icon franchise-enquiry-button-icon-pulse" alt="<?php echo __('Franchise Enquiry'); ?>" title="<?php echo __('Franchise Enquiry'); ?>" class="FranchiseEnquiryLink"><span>Franchise</span><span>Enquiry</span></a>
</div>