
<div class="page-main-actions">
    <div data-mage-init='{"floatingHeader": {}}' class="page-actions"  data-ui-id="page-actions-toolbar-content-header" >
        <!--
        <button id="save" title="save" type="button" class="action-default scalable primary" onclick="setLocation('<?php echo $this->getCreateEmptyUrl(); ?>');"  data-ui-id="adminhtml-order-edit-save-button" >
            <span><?php echo __('Create empty RMA'); ?></span>
        </button>
        -->
        <button id="import" title="import" type="button" class="action-default scalable primary" onclick="setLocation('<?php echo $this->getCreateFromOrderUrl(); ?>');" >
            <span><?php echo __('Create RMA from order'); ?></span>
        </button>
    </div>
</div>
