<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_config = $this->helper('Sm\Market\Helper\Data');
?>

<div class="footer-container footer-style-11">
	<div class="footer-wrapper">
		<div class="footer-top">
			<div class="container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-description-id18')->toHtml(); ?>
				<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
			</div>
		</div>
		
		<div class="footer-middle">
			<div class="container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-services')->toHtml(); ?>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links-id18')->toHtml(); ?>
				
				<div class="copyright-footer">
					<?php if($_config->getAdvanced('custom_copyright')){ ?>
						<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
					<?php } else {?>
						<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
					<?php } ?>
				</div>
				
				<div class="footer-payment">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
	
	<?php if($_config->getAdvanced('show_gototop')){ ?>
		<a id="yt-totop" href="javascript:void(0)" title="Go to Top"></a>
	<?php } ?>
	
</div>




